sudo: required
services:
    - docker
    
env:
    global:
        - SHA=$(git rev-parse HEAD)
        
before_install:
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t rsharma/pyth-test -f ./pythapp/Dockerfile ./pythapp
    
scripts:
    - docker run -d rsharma/pyth-test 
    
deploy:
    provider: scripts
    script: bash ./deploy.sh
    on:
        branch: master
    