apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: pythapp-ingress
    namespace: ingress-nginx
    annotations: 
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    
    rules:
        - host: mypythapp.com
          http:
            paths:
                - path: /?(.*)
                  backend:
                    serviceName: pythapp-cluster-ip-service
                    servicePort: 5000
    tls:
        - hosts:
            - mypythapp.com
        secretName: mypythapp-com-tls